name: CI
on: [push]
jobs:
  builds:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.1.0f2
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
        
      - name: Decrypt the license file
        run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf
        
      - name: Activate Unity
        run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2018.x.ulf || exit 0
        
      - name: Build Windows Player
        run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -noUPM -logFile -projectPath . -buildWindows64Player ./bin-win64/CISample.exe
        
      - name: Archive Windows Build
        uses: actions/upload-artifact@v1
        with:
          name: CISampleWin64Binary
          path: ./bin-win64
          
